#ifndef VECC_DEFINED
#define VECC_DEFINED 1

// WARNING: this file was generated by the VecC compiler.

#include <stdint.h>
#include <stdio.h>
#include <immintrin.h>

// VECC type definitions
typedef int8_t bool8_t;
typedef int16_t bool16_t;
typedef int32_t bool32_t;
typedef int64_t bool64_t;

// VECC exported function declarations
int32_t bar(int32_t a);
void vecc_main();

// VECC exported global variable declarations
#endif // VECC_DEFINED


#ifdef VECC_IMPL
// VECC private function declarations

// VECC private global variable declarations

// VECC function definitions
int32_t bar(int32_t a) {
	for (int64_t i = 0; i < (int64_t)16; i += (int64_t)1) {
		a += (int32_t)i;
	};
	if (a > 100) {
		a += 2;
	} else {
		int32_t b = a / 2;
		return a + b;
	};
	return a;
}

void vecc_main() {
}

#endif // VECC_IMPL