#ifndef VECC_DEFINED
#define VECC_DEFINED 1

// WARNING: this file was generated by the VecC compiler.

#include <stdint.h>
#include <stdio.h>
#include <vecc_builtin.h>


// VECC exported constants


// VECC exported function declarations
void main_vecc();
#endif // VECC_DEFINED


#ifdef VECC_IMPL

// VECC private function declarations


// VECC global variable declarations


// VECC function definitions

void main_vecc() {
	string_println({"Hello World!", 12});
}

#endif // VECC_IMPL
