#ifndef VECC_DEFINED
#define VECC_DEFINED 1

// WARNING: this file was generated by the VecC compiler.

#include <stdint.h>
#include <stdio.h>
#include <immintrin.h>
#ifdef __cplusplus
#else // __cplusplus
#define false 0
#define true 1
#endif // __cplusplus

// VECC type definitions
typedef int8_t bool8_t;
typedef int16_t bool16_t;
typedef int32_t bool32_t;
typedef int64_t bool64_t;
typedef struct Aos2_float { float data[2]; } Aos2_float;
typedef struct Enemy {
	Aos2_float pos;
	float health;
	int32_t ammo;
} Enemy;

// VECC exported function declarations
void main_vecc();
#endif // VECC_DEFINED


#ifdef VECC_IMPL

// VECC private function declarations

static void deal_damage(Enemy* enemy, float damage);

// VECC global variable declarations

const int32_t CONSTANT = 123;
const float FOO = 1.2f;

// VECC function definitions

static void deal_damage(Enemy* enemy, float damage) {
	enemy->health -= damage;
}

void main_vecc() {
	Enemy enemy = {0};
	enemy.health = FOO;
	enemy.ammo = 1;
	enemy.pos.data[0] = 123.0f;
	enemy.pos.data[1] = 1.0f;
	deal_damage(&enemy, 2.0f);
}

#endif // VECC_IMPL
